-- Seed: 34 tỉnh/thành phố hiện hành (theo mục XIII của yêu cầu)
insert into provinces (province_code, province_name, province_type, sort_order) values
  ('HN', 'Hà Nội', 'thanh_pho_tw', 1),
  ('HP', 'Hải Phòng', 'thanh_pho_tw', 2),
  ('HUE', 'Huế', 'thanh_pho_tw', 3),
  ('DN', 'Đà Nẵng', 'thanh_pho_tw', 4),
  ('CT', 'Cần Thơ', 'thanh_pho_tw', 5),
  ('HCM', 'Thành phố Hồ Chí Minh', 'thanh_pho_tw', 6),
  ('CB', 'Cao Bằng', 'tinh', 7),
  ('DB', 'Điện Biên', 'tinh', 8),
  ('LC1', 'Lai Châu', 'tinh', 9),
  ('SL', 'Sơn La', 'tinh', 10),
  ('LS', 'Lạng Sơn', 'tinh', 11),
  ('TQ', 'Tuyên Quang', 'tinh', 12),
  ('LC2', 'Lào Cai', 'tinh', 13),
  ('TN1', 'Thái Nguyên', 'tinh', 14),
  ('QN1', 'Quảng Ninh', 'tinh', 15),
  ('BN', 'Bắc Ninh', 'tinh', 16),
  ('PT', 'Phú Thọ', 'tinh', 17),
  ('HY', 'Hưng Yên', 'tinh', 18),
  ('NB', 'Ninh Bình', 'tinh', 19),
  ('TH', 'Thanh Hóa', 'tinh', 20),
  ('NA', 'Nghệ An', 'tinh', 21),
  ('HT', 'Hà Tĩnh', 'tinh', 22),
  ('QT', 'Quảng Trị', 'tinh', 23),
  ('QNg', 'Quảng Ngãi', 'tinh', 24),
  ('GL', 'Gia Lai', 'tinh', 25),
  ('KH', 'Khánh Hòa', 'tinh', 26),
  ('DL', 'Đắk Lắk', 'tinh', 27),
  ('LD', 'Lâm Đồng', 'tinh', 28),
  ('DNa', 'Đồng Nai', 'tinh', 29),
  ('TNi', 'Tây Ninh', 'tinh', 30),
  ('VL', 'Vĩnh Long', 'tinh', 31),
  ('DT', 'Đồng Tháp', 'tinh', 32),
  ('CM', 'Cà Mau', 'tinh', 33),
  ('AG', 'An Giang', 'tinh', 34);
