-- Seed: 64 Cục/đơn vị trực thuộc Bộ Công an (nguồn: DANH_SÁCH_CÁC_ĐƠN_VỊ_CẤP_CỤC.docx)
-- X03 (Cục Công tác chính trị) được đánh dấu is_owner = true theo mục XII của yêu cầu
insert into units (unit_code, unit_name, unit_type, is_owner, sort_order) values
  ('V01', 'Văn phòng Bộ Công an', 'cuc', false, 1),
  ('V02', 'Cục đối ngoại', 'cuc', false, 2),
  ('V03', 'Cục Pháp chế và Cải cách hành chính, Tư pháp', 'cuc', false, 3),
  ('V04', 'Cục Khoa học, chiến lược và lịch sử Công an', 'cuc', false, 4),
  ('V05', 'Cục xây dựng phong trào Bảo vệ ANTQ', 'cuc', false, 5),
  ('V06', 'Cục Hồ sơ nghiệp vụ', 'cuc', false, 6),
  ('A01', 'Cục An ninh đối ngoại', 'cuc', false, 7),
  ('A02', 'Cục An ninh nội địa', 'cuc', false, 8),
  ('A03', 'Cục An ninh chính trị nội bộ', 'cuc', false, 9),
  ('A04', 'Cục An ninh kinh tế', 'cuc', false, 10),
  ('A05', 'Cục An ninh mạng và phòng chống tội phạm công nghệ cao', 'cuc', false, 11),
  ('A06', 'Cục Kỹ thuật nghiệp vụ', 'cuc', false, 12),
  ('A07', 'Cục Ngoại tuyến', 'cuc', false, 13),
  ('A08', 'Cục Quản lý xuất nhập cảnh', 'cuc', false, 14),
  ('A09', 'Cục An ninh điều tra', 'cuc', false, 15),
  ('B01', 'Cục B01', 'cuc', false, 16),
  ('B02', 'Cục B02', 'cuc', false, 17),
  ('B03', 'Cục B03', 'cuc', false, 18),
  ('B04', 'Cục B04', 'cuc', false, 19),
  ('B05', 'Cục B05', 'cuc', false, 20),
  ('B06', 'Cục B06', 'cuc', false, 21),
  ('C01', 'Văn phòng Cơ quan Cảnh sát điều tra', 'cuc', false, 22),
  ('C02', 'Cục Cảnh sát hình sự', 'cuc', false, 23),
  ('C03', 'Cục Cảnh sát kinh tế', 'cuc', false, 24),
  ('C04', 'Cục Cảnh sát điều tra tội phạm về ma túy', 'cuc', false, 25),
  ('C05', 'Cục Cảnh sát phòng, chống tội phạm về môi trường', 'cuc', false, 26),
  ('C06', 'Cục Cảnh sát Quản lý hành chính về TTXH', 'cuc', false, 27),
  ('C07', 'Cục Cảnh sát PCCC và CNCH', 'cuc', false, 28),
  ('C08', 'Cục Cảnh sát giao thông', 'cuc', false, 29),
  ('C09', 'Viện khoa học hình sự', 'cuc', false, 30),
  ('C10', 'Cục Cảnh sát QL Trại giam, Cơ sở giáo dục, Trường giáo dưỡng', 'cuc', false, 31),
  ('C11', 'Cục CẢnh sát quản lý tạm giam, tạm giữ và thi hành án hình sự tại cộng đồng', 'cuc', false, 32),
  ('C12', 'Trung tấm dữ liệu quốc gia', 'cuc', false, 33),
  ('D01', 'Tổng công ty Viễn thông Mobifone', 'cuc', false, 34),
  ('D02', 'Tổng công ty công nghệ - Viễn thông toàn cầu Gtel', 'cuc', false, 35),
  ('X01', 'Cục Tổ chức cán bộ', 'cuc', false, 36),
  ('X02', 'Cục đào tạo', 'cuc', false, 37),
  ('X03', 'Cục Công tác chính trị', 'cuc', true, 38),
  ('X04', 'Cục Truyền thông CAND', 'cuc', false, 39),
  ('X05', 'Thanh tra Bộ Công an', 'cuc', false, 40),
  ('X06', 'Cơ quan UBKT Đảng ủy Công an Trung ương', 'cuc', false, 41),
  ('K01', 'Bộ Tư lệnh Cảnh vệ', 'cuc', false, 42),
  ('K02', 'Bộ Tư lệnh Cảnh sát cơ động', 'cuc', false, 43),
  ('H01', 'Cục Kế hoạch tài chính', 'cuc', false, 44),
  ('H02', 'Cục Quản lý xây dựng và doanh trại', 'cuc', false, 45),
  ('H03', 'Cục Trang bị và Kho vận', 'cuc', false, 46),
  ('H04', 'Cục Viễn thông và cơ yếu', 'cuc', false, 47),
  ('H05', 'Cục Công nghệ thông tin', 'cuc', false, 48),
  ('H06', 'Cục Y tế', 'cuc', false, 49),
  ('H07', 'Cục Hậu cần', 'cuc', false, 50),
  ('H08', 'Cục Công nghiệp An ninh', 'cuc', false, 51),
  ('T01', 'Học viện An ninh Nhân dân', 'cuc', false, 52),
  ('T04', 'Đại học An ninh Nhân dân', 'cuc', false, 53),
  ('T08', 'Trường Cao đẳng An ninh Nhân dân', 'cuc', false, 54),
  ('T02', 'Học viện Cảnh sát Nhân dân', 'cuc', false, 55),
  ('T05', 'Đại học Cảnh sát Nhân dân', 'cuc', false, 56),
  ('T09', 'Trường Cao đẳng Cảnh sát Nhân dân I', 'cuc', false, 57),
  ('T06', 'Học viện Phòng cháy chữa cháy và cứu nạn cứu hộ', 'cuc', false, 58),
  ('T07', 'Học viện kỹ thuật và công nghệ an ninh', 'cuc', false, 59),
  ('T10', 'Trường Cao đẳng Cảnh sát nhân dân II', 'cuc', false, 60),
  ('BV01', 'Bệnh viện 19/8', 'cuc', false, 61),
  ('BV02', 'Bệnh viện Y học Cổ truyền', 'cuc', false, 62),
  ('BV03', 'Bệnh viện 199', 'cuc', false, 63),
  ('BV04', 'Bệnh viện 30/4', 'cuc', false, 64);

-- Seed: 34 đơn vị Công an tỉnh/thành phố (1-1 với bảng provinces, mục XI)
insert into units (unit_code, unit_name, unit_type, province_id, sort_order)
select 'CA-' || province_code, 'Công an ' || province_name, 'congan_tinh', province_id, 1000 + sort_order
from provinces;